### ISSUE TITLE
Move base request url to configuration option.

### ISSUE THREAD

**Issue by Jabronironi** [arex388/Arex388.Geocodio#1]
First, thank you for this library. Saved me some time, and looks nice and clean.

I did notice something while I was trying to use it.  I was looking for where I set the endpoint value, and noticed you can't (it is hard coded).  It would be great if there was a way to configure this so I could load from a configuration file.  Just feels better than having a hard coded endpoint somewhere.  This is probably something that changes rarely, but still feels like a best practice.  Thank you!

**Comment by arex388** [comment]
Hey @RemyArmstro, thanks for the kind words and sorry for the late reply, I just saw your question when I was publishing the 1.1.0 update.

I briefly looked at the endpoint and it seems like the only thing that changes is the version number, and some properties that were renamed between versions. So, I've changed it up a bit to where in the `GeocodioClient` constructor you can now pass in the endpoint version you want using the new `EndpointVersions` constants. By default the client will always default to the latest, but you can now at least specify the older versions for backwards compatibility.

The older version responses have also been updated for backwards compatibility. I should have had this in from the beginning in hindsight because it was easier than I thought it would be to implement.

This is probably as configurable as the endpoint will get because the endpoint root and method paths will always be the same (well, presumably, it would have to be a huge breaking change to alter them). If that changes in the future then I will look at it again. This update will be marked 1.2.0.

Would this be close to what you had in mind?

**Comment by arex388** [comment]
It's been two months so I assume the issue has been resolved so I will close it for now. If not, please leave a comment and I'll investigate some more. Thanks!
