### ISSUE TITLE
Accept keyed list for batch processing

### ISSUE THREAD

**Issue by jimkilliansentinel** [arex388/Arex388.Geocodio#10]
I need to submit a batch of points that each have a key (https://www.geocod.io/docs/#batch-reverse-geocoding doesn't specify a format, but I was able to make it work by adapting the example at https://www.geocod.io/docs/#batch-geocoding):
    {"11N 49417 364605":"32.952829,-117.062303","11N 49421 364608":"32.953046,-117.06191",...
For ReverseGeocodeBatchAsync, I created a List<string> like this:
    ""11N 49417 364605":"32.952829,-117.062303""
But it returns results where the ResponseStatus = Success and Results is empty.

I wasn't able to find a way to pass a keyed list so that the results would be keyed as well.

Any chance this can be modified to optionally accept a Dictionary<string, string> or similar construct and return the appropriately keyed list?

Thanks!

**Comment by arex388** [comment]
@jimkilliansentinel My apologies, I just saw this issue request. I've chosen to not do the keyed batch processing because it just adds too much complexity. The API processes batch requests in the same exact order it receives it, so it should be a simple index match. Additionally I've just released v2.0.0 which is a complete overhaul and rewrite of the whole client. It does have breaking changes, but I believe they're for the better. Take a peek if you're still using this library. Thanks!
