### ISSUE TITLE
Adding census field to batch geocoding request?

### ISSUE THREAD

**Issue by ghost** [arex388/Arex388.Geocodio#2]
I noticed this line in the code

    public async Task<GeocodeBatchResponse> GetGeocodeBatchAsync(
			IList<string> addresses,
			params string[] fields) => await GetGeocodeBatchAsync(new GeocodeBatchRequest {
			Addresses = addresses,
			Fields = fields
		});

![image](https://user-images.githubusercontent.com/37348520/54292477-4527ac80-457c-11e9-86ad-b1669d8ac859.png)

But I am unable to have the field options work when I try something like this:

     var geocodeBatch = await _geocodio.GetGeocodeBatchAsync(
                            geocodeFormatCollection, "census");

And like these:

    var geocodeBatch = await _geocodio.GetGeocodeBatchAsync(geocodeFormatCollection, fields: 
        "census");

    var geocodeBatch = await _geocodio.GetGeocodeBatchAsync(geocodeFormatCollection, new[] 
        {"census"});

    var geocodeBatch =   await _geocodio.GetGeocodeBatchAsync(geocodeFormatCollection, fields: new[] 
         {"census"});

    string[] fields = new string[] {"census"};
     var geocodeBatch =    await _geocodio.GetGeocodeBatchAsync(geocodeFormatCollection, fields );

It still runs but nothing is appended?  Curious if there was a way to explain this in the ReadMe or if I am missing something. I have tried other fields like acs-demographics and still no result.

**Comment by arex388** [comment]
Hey @peterjf2, sorry about that. It was indeed a bug in the code. When I was composing the batch request, I had the fields parameter mistyped as "field" instead of "field**s**".

I've fixed it an have just published an updated 1.2.1 NuGet package. It should be available in about 15 minutes from when I write this. Please update to it and let me know if you're getting the results correctly now.

Also, there's a convenience helper class, `FieldTypes`, that contains all of the available strings. I recommend using it instead of manually typing them out. Thanks!

**Comment by ghost** [comment]
Awesome.  Thanks, I think I ended up using swift in some of my examples trying to figure it out haha.  Everything works fine now.  The helper class is great.  Thanks for the quick response.
