### ISSUE TITLE
Consider adding a license?

### ISSUE THREAD

**Issue by srajkovic** [arex388/Arex388.Geocodio#8]
This is a really nice wrapper around Geocod.io's APIs, thank you for sharing! I was wondering, do you have any intention of add a license (like MIT or Apache 2)? Just want to make sure I wouldn't be running afoul of any licensing requirements by using the library. Thanks!

**Comment by arex388** [comment]
Hey @srajkovic, I promise I haven't been ignoring you on purpose all this time, I just saw your comment since I don't visit the repository too often, so I apologize for the delay.

As for the license, I don't really know much about licenses so I left it off. I'm open to any recommendations you have on what license type should be added. Thanks!

**Comment by srajkovic** [comment]
No problem! I personally like the MIT license because it’s simple and permissive. I’m not as familiar with copy-left licenses like the GPL, but those are more restrictive. Snyk has a decent guide here: https://snyk.io/learn/open-source-licenses/

**Comment by arex388** [comment]
Weirdly in another repository I had a pull request came in today, around the same time you commented, to add an MIT license, so I went with it here as well.

**Comment by srajkovic** [comment]
Awesome!
